apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin
spec:
  # defaultBackend:
  #   service:
  #     name: {{ .Values.replica.appName }}
  #     port:
  #       number: 80
  ingressClassName: nginx
  rules:
    - host: httpbin.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.balancer.appName }}
                port:
                  number: {{ .Values.balancer.ports.http }}
