---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.balancer.appName }}
spec:
  ports:
    - port: {{ .Values.balancer.ports.http }}
      targetPort: http
  selector:
    ods.service: {{ .Values.balancer.appName }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.primary.appName }}
spec:
  ports:
    - port: {{ .Values.primary.ports.http }}
      targetPort: http
  selector:
    ods.service: {{ .Values.primary.appName }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.replica.appName }}
spec:
  ports:
    - port: {{ .Values.replica.ports.http }}
      targetPort: http
  selector:
    ods.service: {{ .Values.replica.appName }}
